INSERT INTO categoria (descricao) VALUES ('CLAMOR');
INSERT INTO categoria (descricao) VALUES ('INVOCAÇÃO E COMUNHÃO');
INSERT INTO categoria (descricao) VALUES ('DEDICAÇÃO');
INSERT INTO categoria (descricao) VALUES ('MORTE, RESSURREIÇÃO E SALVAÇÃO');
INSERT INTO categoria (descricao) VALUES ('CONSOLO E ENCORAJAMENTO');
INSERT INTO categoria (descricao) VALUES ('SANTIFICAÇÃO E DERRAMAMENTO DO ESPÍRITO SANTO');
INSERT INTO categoria (descricao) VALUES ('VOLTA DE JESUS E ETERNIDADE');
INSERT INTO categoria (descricao) VALUES ('LOUVOR');
INSERT INTO categoria (descricao) VALUES ('SALMOS DE LOUVOR');
INSERT INTO categoria (descricao) VALUES ('GRUPO DE LOUVOR');
INSERT INTO categoria (descricao) VALUES ('CORINHOS');