UPDATE hino SET categoria_id = 1 WHERE coletanea_id = 1 AND CAST(numero AS int) <= 56;
UPDATE hino SET categoria_id = 2 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 57 AND 96;
UPDATE hino SET categoria_id = 3 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 97 AND 200;
UPDATE hino SET categoria_id = 4 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 201 AND 294;
UPDATE hino SET categoria_id = 5 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 295 AND 385;
UPDATE hino SET categoria_id = 6 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 386 AND 477;
UPDATE hino SET categoria_id = 7 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 478 AND 571;
UPDATE hino SET categoria_id = 8 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 572 AND 649;
UPDATE hino SET categoria_id = 9 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 650 AND 665;
UPDATE hino SET categoria_id = 10 WHERE coletanea_id = 1 AND CAST(numero AS int) BETWEEN 666 AND 730;
UPDATE hino SET categoria_id = 11 WHERE coletanea_id = 1 AND CAST(numero AS int) >= 731;